id = "sqruff"
name = "Sqruff"
description = "Support for Sqruff, the SQL linter and formatter"
version = "0.1.0"
schema_version = 1
authors = []
repository = "https://github.com/quarylabs/sqruff"

[language_servers.sqruff]
name = "Sqruff"
languages = ["SQL"]
